language: objective-c
osx_image: xcode7.3
sudo: false
before_install:
  - brew update
  - brew outdated xctool || brew upgrade xctool
install: true
env:
  matrix:
    - XCODE_SCHEME="libPusher" SDK="iphonesimulator"
    - XCODE_SCHEME="libPusher-OSX" SDK="macosx"
    - XCODE_SCHEME="Functional Specs" SDK="iphonesimulator"
script: xctool -workspace libPusher.xcworkspace -scheme "$XCODE_SCHEME" -sdk "$SDK" test
