language: objective-c
osx_image: xcode7.3
sudo: false
before_install:
  - brew update
  - brew outdated xctool || brew upgrade xctool
install:
  - tail -n +4 Sample/Constants.h.example > Sample/Constants.h
  - echo \#define PUSHER_APP_ID @\"$(env | grep PUSHER_APP_ID | cut -d "=" -f 2)\" >> Sample/Constants.h
  - echo \#define PUSHER_API_KEY @\"$(env | grep PUSHER_API_KEY | cut -d "=" -f 2)\" >> Sample/Constants.h
  - echo \#define PUSHER_API_SECRET @\"$(env | grep PUSHER_API_SECRET | cut -d "=" -f 2)\" >> Sample/Constants.h
  - bundle install
env:
  matrix:
    - XCODE_SCHEME="libPusher" SDK="iphonesimulator"
    - XCODE_SCHEME="libPusher-OSX" SDK="macosx"
    - XCODE_SCHEME="Functional Specs" SDK="iphonesimulator"
script:
  - rackup -p 9292 Scripts/auth_server.ru > logs.txt 2>&1 &
  - xctool -workspace libPusher.xcworkspace -scheme "$XCODE_SCHEME" -sdk "$SDK" test
after_success:
  - nscurl --ats-diagnostics https://api.pusherapp.com
  - sleep 5